server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: medicine-web
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html